version: "3.7"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:7.0.9-rc0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - v_mongo:/data/db
    env_file:
      - db.env
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  v_mongo:
